language: node_js
env:
  global:
  - SINGPATH_RULES_E2E_FIREBASE_ID=singpath-travis
  - secure: LMstezQ3BhQw3M5Hq8ioHO45leDzCA/mLoCCrCmRyCan8yxT7Xe+dqooPfzK22OF7UvwIJcsO1wGfgOrnkQWaEgdI8ZGoEyjd7wVD5+OAdEqH1h/RKRWF2iMIsCeK+ol1H5kzoVMWYd2O19GLi6ER7FCK55yOdDUOMEo9Tt2LbRt0UlXTMCfmHSGVYZrfRN0rV/lEFoaoSQxVuJ/khF9xOpw74/W7HNYa90qHBO05b26i0gPYMusO8gyJRJzjxI/31BeYBZxVVsjx8qHJf/Odt9+3haA0AjNt0O1i3Yk/aPHs2wLALSHuwTTjyLRho7sBjOgrzZD9d4dEjqGHWeTLRrU3ZrMLX4rod10Bb+TAmsgudc+iiYIX/62QvCIZ9ZmFbtuhtPFqtXDy25gjLagRWhCAllsbOpxvacPLVwICoyXrOlbETIvXQ6sFvR0GyUXS/nvLbTVWKEYc5kNKeQoNSa2PwER0hA7MfHwu2aF+p0ySPxdW86hHsqo0AYqf5gCKj2bN3wXX7g+lIzjg9JKKGxpkK4fNS995QnPqlwhu6MbDic9nwqAzQ9c5R37k7lv3Q6Dsae4zuq9WKFXzHsvncEkfPc9JLUNK11kVIBa70Ak7oSAsz47DoLQd/i7Rb6j0j0kQu2DXwrWjBLW4/nwNucA+ux6Qa5yxGGuGdq2E7k=
node_js:
- '4.2'
install:
- npm install
script:
- npm run lint
- npm run test
- npm run coveralls
- test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || ./bin/singpath-rules upload-rules -f $SINGPATH_RULES_E2E_FIREBASE_ID --secret=$SINGPATH_RULES_E2E_FIREBASE_SECRET
- test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || npm run test-e2e
