language: node_js
env:
  global:
  - SINGPATH_RULES_E2E_FIREBASE_ID=singpath-travis
  - secure: dpQnMEYXhzTbkIr2yUF4LCepEr+tY1HPXhwKGOQDUCK1DYBCUyRSFX+XEldjgtMwJLMatDKMNfDwcd0AG0TGAL7O+phRynyKUdlzHcx0qGmHISRakEoyW1iesJZnyk82uKSv52lMPXeCFgyIqVA5yUUYLIGcQU/KemrhVYzy1NTxCd8myVMSUgF9FmYZFGn9jRfl9O7+MMUovPSjOIs8urDiRXNgR+2nBG6kpkL+6QaWdsBTpPPgK6cxm8PgtfeuqC1c3QpSM1+Bj4wpJmCTzgrrVeYqHl8bufT0bc6npWWyPi7bvXCrsrzGIC8DTZcE/FQ8H/VXw7fP3CI5P3rW0lkxkccI+mpYmHhKKI0ORuWaPH15LFagcFlpfBxIwE0aHcfDXFTApEA/k5LCAvUHn+7PVfMw/MC0vrqdvR78thCrIZE1+81PGcMwfXUbt/W6mlKYVYNOaCqq8G8CA5UrvyAAE4oFP95GL/owgKEg+PRyiIt/ZhvyIZ/vw+TtsJlxKmAfSrxSU8L+JCEVAgezjbk4cbBuxAeBdUyBzHdP4bVNJdW6doHaFaMviI3MY0cVYoXiwfGrlO0pAogPHAxiCWzIEKFq7XtYmb4y8C5QVSY4erAHMvNM11PkSEkP9AtKt7kajQ9HJFnnGEQyXLahN7IqaKuJ7dEJ7WVfh2dijYc=
  - secure: im1Dn8mWKR4C/QJDv40CprS8AvG/SN/WukhxnXUlulEI89jFbAmbrUp+WO1ifr+QkOZeqROBMXDP0dOmL5y+0p7F5xBzu3tGHMEFhtXcEXzfTguzK/KXPBXmIqWgqFeFEaBOPZR+ChhYzgzh6MBIa+Iczt4vguQ5K6VG0rVeFuwC3q1vgs1yi3jbt+YAUKjNVLp995dNDluOfYjH6xBSqU6DsV9mFm7L8T/DmkhnufcIu3uZ4wkGdcVFB4OyneEZhtga36uKAJ8UoVgzAiu8gZZ5MPJWmpR6HUSBNxPkqr9XSv5y59uo+6I+lbq/Xt7Jf3T+OMPxI1E+VD79Al8cAEe3At+ahCVua0XHNFFnWNpRH6GhjCAmh4VcK7Ofl8qFPsodGTQTPZE/J1+ST41Xs1SgCGh5tJOhzH1uNC6mKm9FB9qculhNs++49bsEIDIajb3avBmUii0dkEpadcTcAeINYLvcKdfuMHNeHX+J748hgPJcU1h3PpsSX+LiOI4KjaEMsm5ez3f68hyji+RjhBE4ZFgmsjgY51/VdJzijOHrfvUYecj8Un1lFFXDWPJF9v8FHrLMHLhTw80YkAmqG4s9iPswmJKnsmM+jKRsFB9fWI5n8LWuZGpwqiZPwF5/oc4JJMgVXQXXG40vWWF+lV9zEVw5mHtxJrbaRKkv7IQ=
node_js:
- '4.2'
install:
- npm install
script:
- 'npm run lint'
- 'npm run test'
- 'npm run coveralls'
- 'test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || test -z "$SINGPATH_RULES_TOKEN" || ./bin/singpath-rules upload-rules -f $SINGPATH_RULES_E2E_FIREBASE_ID --token $SINGPATH_RULES_TOKEN'
- 'test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || test -z "$SINGPATH_RULES_TOKEN" || npm run test-e2e'
